#### general settings
name: FSRCNN_branch1
use_tb_logger: true
model: sr
distortion: sr
scale: 4
gpu_ids: [0]

#### network structures
network_G:
  which_model_G: fsrcnn
  in_nc: 3
  out_nc: 3
  upscale: 4
  d: 16
  s: 12
  m: 4

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT
    dataroot_GT: /data0/xtkong/data/DIV2K_scale_sub_psnr_GT_class1
    dataroot_LQ: /data0/xtkong/data/DIV2K_scale_sub_psnr_LR_class1


    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: set5
    mode: LQGT
    dataroot_GT: /data0/xtkong/ClassSR/datasets/Set5/HR.lmdb
    dataroot_LQ: /data0/xtkong/ClassSR/datasets/Set5/LR.lmdb


#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-3
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 500000
  warmup_iter: -1  # no warm up
  T_period: [500000]
  restarts: [500000]
  restart_weights: [1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 5000

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000
